/**
 * Generates `lib/countries.generated.ts` from the dataset.
 *
 * For every country that appears in `data/players.generated.json` (as a
 * citizenship, represented nation, or birth country) it resolves:
 *   - an ISO 3166-1 alpha-2 code (for the flag emoji), via i18n-iso-countries
 *     with a few manual overrides;
 *   - the matching world-atlas topojson shape name (for map highlighting).
 *
 * Unmapped countries are logged — they simply won't highlight on the map.
 *
 * Usage: npx tsx scripts/build_countries.ts
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import countries from "i18n-iso-countries";
import enLocale from "i18n-iso-countries/langs/en.json" assert { type: "json" };

countries.registerLocale(enLocale);

const DATA = resolve(process.cwd(), "data", "players.generated.json");
const TOPO = resolve(process.cwd(), "public", "world-110m.json");
const OUT = resolve(process.cwd(), "lib", "countries.generated.ts");

// Canonical name -> ISO2 overrides (names i18n-iso-countries misses/varies on).
const ISO_OVERRIDES: Record<string, string> = {
  England: "GB", Scotland: "GB", Wales: "GB", "Northern Ireland": "GB",
  "Ivory Coast": "CI", "DR Congo": "CD", Congo: "CG", "Cape Verde": "CV",
  "South Korea": "KR", "North Korea": "KP", Curaçao: "CW", Kosovo: "XK",
  Turkey: "TR", "United States": "US", "Czech Republic": "CZ",
  "North Macedonia": "MK", "Bosnia and Herzegovina": "BA",
  "Saint Kitts and Nevis": "KN", "Trinidad and Tobago": "TT",
  "South Sudan": "SS",
};

// Canonical name -> topojson `properties.name`, when it differs.
const GEO_OVERRIDES: Record<string, string> = {
  // UK home nations are drawn as their own shapes (public/uk-nations.json),
  // keyed by their canonical names.
  England: "England", Scotland: "Scotland", Wales: "Wales",
  "Northern Ireland": "Northern Ireland",
  "United States": "United States of America",
  "Ivory Coast": "Côte d'Ivoire",
  "DR Congo": "Dem. Rep. Congo",
  "Czech Republic": "Czechia",
  "Bosnia and Herzegovina": "Bosnia and Herz.",
  "North Macedonia": "Macedonia",
  "Equatorial Guinea": "Eq. Guinea",
  "Cape Verde": "Cabo Verde",
  "Central African Republic": "Central African Rep.",
  "Dominican Republic": "Dominican Rep.",
  "South Sudan": "S. Sudan",
};

interface Player {
  represented_country: string;
  birth_country: string;
  citizenships: string[];
}

function main() {
  if (!existsSync(DATA)) {
    console.error(`✖ ${DATA} not found. Run the fetch pipeline first.`);
    process.exit(1);
  }

  const players: Player[] = JSON.parse(readFileSync(DATA, "utf8"));
  const topo = JSON.parse(readFileSync(TOPO, "utf8"));
  const geoNames = new Set<string>(
    topo.objects.countries.geometries.map((g: { properties: { name: string } }) => g.properties.name)
  );

  const names = new Set<string>();
  for (const p of players) {
    names.add(p.represented_country);
    names.add(p.birth_country);
    for (const c of p.citizenships) names.add(c);
  }

  const meta: Record<string, { iso2: string; geo?: string }> = {};
  const unresolvedIso: string[] = [];
  const unresolvedGeo: string[] = [];

  for (const name of [...names].sort()) {
    const iso2 = ISO_OVERRIDES[name] ?? countries.getAlpha2Code(name, "en") ?? "";
    if (!iso2) unresolvedIso.push(name);

    let geo: string | undefined;
    if (GEO_OVERRIDES[name]) geo = GEO_OVERRIDES[name];
    else if (geoNames.has(name)) geo = undefined; // matches by name already
    else {
      geo = undefined;
      unresolvedGeo.push(name);
    }

    meta[name] = geo ? { iso2, geo } : { iso2 };
  }

  const body = Object.entries(meta)
    .map(([name, m]) => `  ${JSON.stringify(name)}: ${JSON.stringify(m)},`)
    .join("\n");

  const out =
    `// AUTO-GENERATED by scripts/build_countries.ts — do not edit by hand.\n` +
    `// Run \`npm run build:countries\` after refreshing the dataset to regenerate.\n` +
    `import type { CountryMeta } from "./countries";\n\n` +
    `export const GENERATED_COUNTRY_META: Record<string, CountryMeta> = {\n${body}\n};\n`;

  writeFileSync(OUT, out);

  console.log(`✔ Wrote ${Object.keys(meta).length} countries to lib/countries.generated.ts`);
  if (unresolvedIso.length)
    console.warn(`  ⚠ no ISO2 (no flag): ${unresolvedIso.join(", ")}`);
  if (unresolvedGeo.length)
    console.warn(`  ⚠ no map shape (won't highlight): ${unresolvedGeo.join(", ")}`);
}

main();
